### ISSUE TITLE
How to include licence with this library ?

### ISSUE THREAD

**Issue by feelthescintillation** [fusioncharts/angular-fusioncharts#11]
My organization has a licence bought for version 3.4. Can that or for the record any licence bout be used with this plugin (angular2-fusioncharts).

**Comment by ariyankhan** [comment]
@feelthescintillation 
Yes, you can use your licensed version of `FusionCharts` library with `angular2-fusioncharts` plugin. Please follow the steps below to achieve this:

**Step 1:**  create a folder `fusioncharts` in your project root directory and copy licensed version of fusioncharts library files to this folder.
**Step 2:** Import `fusioncharts` library in your `AppModule` as follows:
```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FusionChartsModule } from 'angular2-fusioncharts';

// Import your licenced version of fusioncharts here
import * as FusionCharts from '../../fusioncharts';
import * as Charts from '../../fusioncharts/fusioncharts.charts';
import * as FintTheme from '../../fusioncharts/themes/fusioncharts.theme.fint';

import { AppComponent } from './app.component';

FusionChartsModule.fcRoot(FusionCharts, Charts, FintTheme);

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FusionChartsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
Let me know if you face any problem.

**Comment by ashok1994** [comment]
@feelthescintillation  We recommend now to use a [angular-fusioncharts](https://github.com/fusioncharts/angular-fusioncharts/) , 
 Only changed step will be in step 2 
Change the following line 
`import { FusionChartsModule } from 'angular2-fusioncharts';`
to 
`import { FusionChartsModule } from 'angular-fusioncharts';`

Closing for now , please feel free to reopen , if the problem persists
