### ISSUE TITLE
dataLabelClick event handler does not update angular component field

### ISSUE THREAD

**Issue by gmakharat** [fusioncharts/angular-fusioncharts#117]
Hi there,
I am trying to use `dataLabelClick`, in method, which handles event thrown by `dataLabelClick`, updating component field but it does nothing, is there something which I should consider while working with event handlers?

**Comment by AyanBhadury** [comment]
https://github.com/fusioncharts/angular-fusioncharts#working-with-events

Replace **dataPlotRollOver** with **dataPlotClick** event

**Comment by gmakharat** [comment]
> https://github.com/fusioncharts/angular-fusioncharts#working-with-events
> 
> Replace **dataPlotRollOver** with **dataPlotClick** event

`dataPlotClick` does not work at all with heatmap, using angular-fusioncharts...

**Comment by AyanBhadury** [comment]
@gmakharat https://codesandbox.io/s/angular-column3d-tlxtm?file=/src/app/app.component.ts

For more assistance drop a mail to support@fusioncharts.com with your license details.

**Comment by gmakharat** [comment]
> @gmakharat https://codesandbox.io/s/angular-column3d-tlxtm?file=/src/app/app.component.ts
> 
> For more assistance drop a mail to [support@fusioncharts.com](mailto:support@fusioncharts.com) with your license details.

Thank you, changing to `[events]=events`, from direct method handling from html, helped.
