### ISSUE TITLE
Deprecated @types/fusioncharts package

### ISSUE THREAD

**Issue by jerone** [fusioncharts/angular-fusioncharts#174]
Warning from NPM when installing:

> npm WARN deprecated @types/fusioncharts@3.12.3: This is a stub types definition. fusioncharts provides its own type definitions, so you do not need this installed.

**Comment by AyanBhadury** [comment]
Hello,

The latest version of angular-fusioncharts has just been released that is angular-fusioncharts 4.0.3. This version supports angular version till the latest one. If you want you can upgrade the angular version and test your application.

Here is the npm link :
https://www.npmjs.com/package/angular-fusioncharts/v/4.0.3

Demo - https://github.com/AyanBhadury/angular-fusioncharts-sample

**Comment by lrozenblyum** [comment]
@AyanBhadury the warning about stubs is reproduced with 4.0.3 as well.

**Comment by yklepikovska-iqmessenger** [comment]
we updated to 4.0.3 and have the same issue.

**Comment by jerone** [comment]
@AyanBhadury The fix is super simple; as the above warning and [`@types/fusioncharts` package](https://www.npmjs.com/package/@types/fusioncharts) mentions, just delete this line:

https://github.com/fusioncharts/angular-fusioncharts/blob/develop/dist/package.json#L43
