### ISSUE TITLE
angular2-fusioncharts rc v4

### ISSUE THREAD

**Issue by kindrajeet** [fusioncharts/angular-fusioncharts#19]
I am using your latest version that is rc4 which you guys release last time 6 April 2017 after that there is not release,
Even given example not working in my project i tried a lot i giving issue.
My ng verision 4
If you guys have proper example send me link or guideline.

**Comment by ariyankhan** [comment]
@kindrajeet 
Try to use the latest version [1.0.3](https://github.com/fusioncharts/angular2-fusioncharts/releases/tag/1.0.3) of angular2-fusioncharts and let me know if you face any problem.

I always recommend you to use [angular4-fusioncharts](https://github.com/fusioncharts/angular4-fusioncharts) wrapper built on Angular 4 if your angular version is 4 and above.
You can find `angular2-fusioncharts` examples from [here](https://fusioncharts.github.io/angular2-fusioncharts/) and for `angular4-fusioncharts` examples, click [here](https://fusioncharts.github.io/angular4-fusioncharts/).

**Comment by ashok1994** [comment]
@kindrajeet  we have released latest version for angular-fusioncharts, please refer the latest documentation here . https://github.com/fusioncharts/angular-fusioncharts/ 
It is compatible with angular 2 and above.
Closing for now , reopen if any problem persists
