### ISSUE TITLE
LinkedChart Rendering position at rc-4 and rc-5

### ISSUE THREAD

**Issue by leventozkann** [fusioncharts/angular-fusioncharts#25]
I have 5 report page in my app and the page contains 5 slides. Each slide has its own linked charts. When i upgrade the version to rc-5, every linked chart is openinig over the first chart. (first chart at the first slide.). It should be opening over its parent child.

Angular version: 2.4.8

**Comment by ariyankhan** [comment]
@leventozkann 
Can you please share a sample code which will raise the same at our end?

**Comment by leventozkann** [comment]
Hi @rousan 

I attached the example code. There is two chart data source in json file. The second chart has a linked chart. 

[fusionhtml.txt](https://github.com/fusioncharts/angular-fusioncharts/files/2273688/fusionhtml.txt)
[fusionjson.txt](https://github.com/fusioncharts/angular-fusioncharts/files/2273690/fusionjson.txt)

When clicking on the second chart the detail chart is opening over the first chart.

![screen shot 2018-08-09 at 12 55 43](https://user-images.githubusercontent.com/5239721/43892125-ce2e72aa-9bd3-11e8-9617-8f5253e0302b.png)
![screen shot 2018-08-09 at 12 56 52](https://user-images.githubusercontent.com/5239721/43892132-d1ce0ab0-9bd3-11e8-9f39-5a58f4526b6b.png)

**Comment by ashok1994** [comment]
#32  This issue has been resolved in this pull request,
Please refer the latest documentation and reopen if the problem persists
