### ISSUE TITLE
Incorrect Angular Version for 1.0.3

### ISSUE THREAD

**Issue by jmbalanag** [fusioncharts/angular-fusioncharts#26]
The latest package (1.0.3) is throwing an issue when used in angular 2 projects.
ctorParameters.map  error is thrown due to this.

based on latest source code, it is using angular 4, hence throws error on angular 2 projects.

**Comment by ariyankhan** [comment]
Hi @jmbalanag 
can you provide sample source code that can produce the same error at our end?

**Comment by ashok1994** [comment]
Please refer the latest documentation in  https://github.com/fusioncharts/angular-fusioncharts/
Feel free to reopen if the problem persists, with a scale down sample
