### ISSUE TITLE
Cannot read property 'dispose' of undefined in ngOnDestroy

### ISSUE THREAD

**Issue by kaname52** [fusioncharts/angular-fusioncharts#35]
We use many charts in app and user can switch from one chart type to another (rendered as different components of course). Also charts are rebuilded on window:resize event. If few resize event appear in a row or user switches fast from one chart to another, his console becomes filled with this messages:

![image](https://user-images.githubusercontent.com/7831464/48487851-15fc6b00-e828-11e8-9f21-46f6029e44a3.png)

that comes from angular-fusioncharts component, ngOnDestroy hook. Sometimes this blocks chart rendering, sometimes not (10% of cases - blocks and nothing is rendered).
I believe it's trying to dispose chart config object, but if chart was not fully initialized by the time it gets destroyed, there won't be this object, so nothing to dispose.

**Comment by ashok1994** [comment]
@kaname52  I tried to replicate this with the updated version , using a simple ngIf hook, couldn't able to replicate. Can you please tell which version of angular-fusioncharts you are using

**Comment by kaname52** [comment]
@ashok1994 2.0.2 along with licensed fusioncharts v.3.13.1-sr.1

**Comment by ashok1994** [comment]
I tried this version too, could not replicate the problem, if you can provide me with small scaled version of the example replicating the problem it'll be great @kaname52

**Comment by jcanaan88** [comment]
I'm getting the same issue. Angular 7. 

While chart component is initializing, quickly switch to a view that hides the chart and you get it everytime.

In my specific instance, I have buttons that change each view based on an ngSwitch.

**Comment by vherever** [comment]
@ashok1994, hi, I created a private demo repo to reproduce this error, https://github.com/vherever/fusioncharts-demo
Thank you in advance!

**Comment by rohanoid5** [comment]
@vherever please add me to your private repo. I'll investigate your issue.

**Comment by sguha-fc** [comment]
This message serves as confirmation that you are now successfully registered in our support center.

Registered Email: reply@reply.github.com
Password: a3sleaqvzb

You can visit the Support Desk at any time by going to http://help.fusioncharts.com/

Please do let us know if you have any questions.

Regards,


FusionCharts Team
------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?

**Comment by sguha-fc** [comment]
This message serves as confirmation that you are now successfully registered in our support center.

Registered Email: reply@reply.github.com
Password: gv9p6isp9n

You can visit the Support Desk at any time by going to http://help.fusioncharts.com/

Please do let us know if you have any questions.

Regards,


FusionCharts Team
------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?

**Comment by vherever** [comment]
@rohanoid5 added you too, thank you

**Comment by rohanoid5** [comment]
@vherever this issue has been fixed. Please update `angular-fusioncharts`

**Comment by kaname52** [comment]
@rohanoid5 thank you! 
I believe this PR can be closed now https://github.com/fusioncharts/angular-fusioncharts/pull/57 since it fixes the same issue

**Comment by vherever** [comment]
@rohanoid5 Thank you, it works!
