### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'head' of object '[object HTMLDocument]'

### ISSUE THREAD

**Issue by BossOz** [fusioncharts/angular-fusioncharts#60]
I just follow the instraction for buildin "my first chart" and serving my test project the console shows me this error

`Uncaught TypeError: Cannot assign to read only property 'head' of object '[object HTMLDocument]'
    at Object../node_modules/fusioncharts/fusioncharts.js (fusioncharts.js:13)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)'`

Here my dependencies:

"dependencies": {
    "@angular/animations": "~8.1.3",
    "@angular/common": "~8.1.3",
    "@angular/compiler": "~8.1.3",
    "@angular/core": "~8.1.3",
    "@angular/forms": "~8.1.3",
    "@angular/platform-browser": "~8.1.3",
    "@angular/platform-browser-dynamic": "~8.1.3",
    "@angular/router": "~8.1.3",
    "angular-fusioncharts": "^3.0.2",
    "fusioncharts": "^3.14.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "~8.1.2",
    "@angular/compiler-cli": "~8.1.3",
    "@angular/language-service": "~8.1.3",
    "@angular-devkit/build-angular": "~0.801.2",
    "@types/jasmine": "~3.3.16",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~12.6.8",
    "codelyzer": "^5.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.0.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "tslint": "~5.18.0",
    "ts-node": "~8.3.0",
    "typescript": "^3.4.5"
  }

How can I fix it?
Thank you very much

**Comment by Imthiyas2** [comment]
Same here. Fusion Charts are not working in Angular 8. Can anyone confirm this? Tried the same, given in the official documentation, but no luck.

**Comment by siawo** [comment]
@BossOz @Imthiyas2  The issue is fixed in fusioncharts v3.14.0-sr.1.
Please upgrade the fusioncharts package to v3.14.0-sr.1.

**Comment by BossOz** [comment]
Downgrading to v3.13.5-sr1 is working. I will try to use the latest.

**Comment by BossOz** [comment]
> @BossOz @Imthiyas2 The issue is fixed in fusioncharts v3.14.0-sr.1
> Please upgrade the fusioncharts package to v3.14.0-sr.1

This fixed the issue!
