### ISSUE TITLE
Charts not working with FusionCharts 3.14.0

### ISSUE THREAD

**Issue by ayanbhaduryfc** [fusioncharts/angular-fusioncharts#61]
Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

**Comment by siawo** [comment]
The issue is fixed in fusioncharts v3.14.0-sr.1.
Please upgrade the fusioncharts package to v3.14.0-sr.1.
