### ISSUE TITLE
Unexpected value FusionChartsModule in 3.1.1

### ISSUE THREAD

**Issue by festivus** [fusioncharts/angular-fusioncharts#65]
We were using 3.0.1 with Angular 8.1 and ng build was working fine. When i change to 3.1.1 we get Unexpected value 'FusionChartsModule in node_modules/angular-fusioncharts/dist/angular-fusioncharts.js'

**Comment by yakuzaaaa** [comment]
Hi @festivus , can you show your package.json?

**Comment by festivus** [comment]
{
    "name": "xxx",
    "version": "0.1.1",
    "license": "MIT",
    "repository": "xxx",
    "description": "xxx",
    "scripts": {
        "ng": "ng",
        "build": "ng build",
        "build:prod": "ng build --prod --aot",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular-mdc/web": "0.42.6",
        "@angular/animations": "8.1.0",
        "@angular/cdk": "8.0.2",
        "@angular/common": "8.1.0",
        "@angular/core": "8.1.0",
        "@angular/flex-layout": "8.0.0-beta.26",
        "@angular/forms": "8.1.0",
        "@angular/material": "8.0.2",
        "@angular/material-moment-adapter": "8.0.2",
        "@angular/platform-browser": "8.1.0",
        "@angular/compiler": "8.1.0",
        "@angular/platform-browser-dynamic": "8.1.0",
        "@angular/router": "8.1.0",
        "@angularclass/hmr": "2.1.3",
        "@auth0/angular-jwt": "2.1.0",
        "@ngrx/effects": "8.0.1",
        "@ngrx/entity": "8.0.1",
        "@ngrx/router-store": "8.0.1",
        "@ngrx/store": "8.0.1",
        "@w11k/angular-sticky-things": "1.1.2",
        "angular-fusioncharts": "3.1.1",
        "classlist.js": "1.1.20150312",
        "core-js": "2.6.8",
        "fusioncharts": "3.14.0",
        "hammerjs": "2.0.8",
        "intl": "1.2.5",
        "moment": "2.24.0",
        "rxjs": "6.5.2",
        "web-animations-js": "2.3.1",
        "zone.js": "0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "0.801.0",
        "@angular/cli": "8.1.0",
        "@angular/compiler-cli": "8.1.0"
    }
}

**Comment by festivus** [comment]
Any update?

**Comment by rohanoid5** [comment]
Hey @festivus seems like you're using a version of `angular-fusioncharts` which doesn't exist. The latest released version is [v3.0.3](https://github.com/fusioncharts/angular-fusioncharts/releases/tag/3.0.3). Please update to the latest version.

**Comment by festivus** [comment]
ugh, egg on face. my bad.
