### ISSUE TITLE
unable to update the values while using fc-events

### ISSUE THREAD

**Issue by ayanbhaduryfc** [fusioncharts/angular-fusioncharts#71]
Here is a sandbox demo - https://codesandbox.io/s/angular-1dhf0

**Comment by priyanjitdey94** [comment]
@ayanbhaduryfc While updating data inside the event listener, you have to use `NgZone`. Here's a [working sample](https://codesandbox.io/s/angular-8wz8i).

Also, please check the [official samples](https://fusioncharts.github.io/angular-fusioncharts/#/ex23).
